version: "3.9"
services:
  server:
    build: .
    ports:
      - "9000:9000"
  osrm:
    image: "6e654e0e06b3"
    command: docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /OSRMrouting/data/map.osrm
    ports:
      - "5000:5000"