version: "3.9"

services:
  server:
    build: .
    ports:
      - "443:443"
  osrm:
    container_name: osrm
    image: osrm/osrm-backend
    volumes:
      - "./OSRM/data:/data"
    command: "osrm-routed --algorithm mld /data/map.osrm"
    ports:
      - "5000:5000"
